image: node:latest
stages:
  - test
before_script:
  - npm ci


test:
  stage: test
  script:
     # start the server in the background
    - npm run start:ci &
    - npm run test:ci

  artifacts:
    when: always
    paths:
      - cypress/screenshots/
      - cypress/videos/

